### ISSUE TITLE
binding of matters from different files doesnt work properly

### ISSUE THREAD

**Issue by iaaaka** [kuwisdelu/matter#12]
Page six of [this vignette](https://bioconductor.org/packages/release/bioc/vignettes/matter/inst/doc/matter.pdf) shows how to cbind vectors that holds data from different files, but seems that it works not as intended, at least cbind(x2, y3)[] and cbind(x[,2], y[,3]) produces different results while they are expected to be the same.
![image](https://user-images.githubusercontent.com/9351543/134078893-41fdd96f-f73f-45a0-b678-e867b4ab73d9.png)

**Comment by kuwisdelu** [comment]
Fixed by 1a27cb89a6be63df0aa5c771bcaacae02ef4b93c
