### ISSUE TITLE
argument data is missing with no default

### ISSUE THREAD

**Issue by MASHUOA** [kuwisdelu/matter#13]
Hi, there,
As I was loading the Imzml data,
I found this:
```
		mz <- matter_list(path=file,
			type=Ctypeof(mz.ibdtype),
			offset=mzData(info)[["external offset"]],
			extent=mzData(info)[["external array length"]])
		intensity <- matter_list(path=file,
			type=Ctypeof(intensity.ibdtype),
			offset=intensityData(info)[["external offset"]],
			extent=intensityData(info)[["external array length"]])
```
will trigger the error message: argument "data" is missing with no default

Best,
George

**Comment by kuwisdelu** [comment]
Can you confirm the version of matter you are using and the exact function call (with parameters) that you used?

The source code suggests you are using the updated Cardinal 3.0 but I can't replicate this issue with the updated matter 2.0.

**Comment by MASHUOA** [comment]
I see. I was using Cardinal 2.X.
After an installation through:
`remotes::install_github("kuwisdelu/Cardinal")`
It's working now.
Best,
George

**Comment by kuwisdelu** [comment]
Ah, yes. The Github branches are the development versions of Cardinal and matter (and will therefore sometimes break), so you will need to make sure they are updated and in sync. The stable version is the Bioconductor release.

**Comment by MASHUOA** [comment]
I see.
I found people have to use a specified (latest) version of BiocManager to make Cardinal 3.0 available:
`BiocManager::install(version = "3.16")`
If a pc was pre-installed with BiocManager (3.1.5, e.g.), it might only be able to get the Cardinal 2. X.
Many thanks,
George
