### ISSUE TITLE
`if` missing closing '}'

### ISSUE THREAD

**Issue by shaman-yellow** [kuwisdelu/matter#26]
Oh! There is an obvious error in your latest version that prevents me from installing it!

[<https://github.com/kuwisdelu/matter/blob/devel/R/sgmix.R>
](https://github.com/kuwisdelu/matter/blob/9cc7f179ff4e7c86740759683e68f27a79b4e9ed/R/sgmix.R#L370)

```
        if ( is.matrix(vals) ) {
		ans <- chunkApply(vals, margin, sgmix_int,
			x=x, y=y, r=r, k=k, ...,
        #  Line 371                                ^
	if ( is.list(vals) ) {
		ans <- chunkLapply(vals, sgmix_int,
			x=x, y=y, r=r, k=k, ...,
			nchunks=nchunks, verbose=verbose,
			RNG=TRUE, BPPARAM=BPPARAM)
	}
```

**Comment by kuwisdelu** [comment]
Fixed by https://github.com/kuwisdelu/matter/commit/d1d48e1d256827252bd04021cbc314e578000837

For this kind of simple fix, you can always just submit a pull request.
