### ISSUE TITLE
Matter installation error v2.8

### ISSUE THREAD

**Issue by rromoli** [kuwisdelu/matter#36]
Hi, got this error installing the 2.8 version from within R using `BiocManager::install("matter")`:

```
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘matter’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/00LOCK-matter/00new/matter/libs/matter.so':
  /usr/local/lib/R/site-library/00LOCK-matter/00new/matter/libs/matter.so: undefined symbol: shm_open
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/matter’
* restoring previous ‘/usr/local/lib/R/site-library/matter’

```

I run a remote workstation with: 
OS: Debian GNU/Linux 11 (bullseye) x86_64 
Kernel: 5.10.0-32-amd64

**Comment by kuwisdelu** [comment]
Are you the administrator on this computer? It looks like it can't find `shm_open` which is a standard Linux system call.

You may need to pass in some additional compiler flag, but this appears to be a system-specific issue, as I've not run into it on other Linux installations.

**Comment by rromoli** [comment]
Can you suggest me the compiler flag to use? I encountered the error during
the update from a previous version, not from a fresh install. Did you
change something related in newer ones?

**Comment by kuwisdelu** [comment]
Yes, v2.8 adds support for a shared memory backend to allow zero-copy sharing of in-memory `matter` arrays between different R processes. The missing symbol `shm_open` is the Linux system call for creating or opening a shared memory object.

Matter v2.8 installs on Linux without issue using R's default build process on the Bioconductor build servers (Ubuntu 24.04 x86_64) and on my own virtual machines (Debian 12 arm64), so I am not sure why this would happen on your workstation. Unfortunately, it's not something I can replicate, so it is probably an environment issue that I can't fix.

A quick DuckDuckGo search suggests `-lrt`? I would suggest reaching out to IT or a system administrator if you have one.

**Comment by rromoli** [comment]
I'm the sys admin but onestly I do not understand this strange behaviours...but as you suggested, and after further search, I solved the problem creating a Makevars file containing 
```
CXXFLAGS += -lrt
PKG_LIBS += -lrt
```
putting it into `/root/.R/Makevars`, and than `R CMD INSTALL --clean /path/to/my/package.tar.gz`. Now all works, thanks!
